export const apartment = [
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
  {
    double: [
      {
        id: 614,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/1v.png",
      },
      {
        id: 3,
        roomQuantity: 2,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/2/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/2/2v.png",
      },
    ],

    triple: [
      {
        id: 614,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/1s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/1v.png",
      },
      {
        id: 3,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/2s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/2v.png",
      },
      {
        id: 4,
        roomQuantity: 3,
        area: 15.0,
        floor: 1,
        price: 152,
        balcony: 45641.0,
        bedroom: 5645.0,
        bathroom: 123.0,
        hall: 56456.0,
        kitchen: 23132.0,
        dining_room: 21.0,
        living_room: 2.0,
        image: null,
        image_2d: "https://www.modernsergeli.uz/assets/img/apartments/3/3s.png",
        image_3d: "https://www.modernsergeli.uz/assets/img/apartments/3/3v.png",
      },
    ],
  },
];
